version: '3.8'

services:
  frontend:
    image: frontend
    build:
      context: ./frontend
      args:
        - REACT_APP_BACKEND_URL=http://localhost:8080
    ports:
      - 5000:5000
  backend:
    image: backend
    build: ./backend
    environment:
      - REQUEST_ORIGIN=http://localhost:5000
      - REDIS_HOST=cache
      - POSTGRES_HOST=db
      - POSTGRES_USER=devops
      - POSTGRES_PASSWORD=ru13z
      - POSTGRES_DATABASE=mandatory
    ports:
      - 8080:8080
    depends_on:
      - cache
  cache:
    image: 'redis:7-alpine'
  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_PASSWORD=ru13z
      - POSTGRES_USER=devops
      - POSTGRES_DB=mandatory
    container_name: db_mandatory
    volumes:
      - ./database:/var/lib/postgresql/data
